model:
  model_path: "finetuned_student_model/"  # Name of hf model to load
  tokenizer_path: "finetuned_student_model/"  # Name of hf tokenizer to load
  model_type: "AccelerateILQLModel"  # Name of accelerate model type to load
  num_layers_unfrozen: -1  # Number of bottom layers to freeze during training


train:
  seq_length: 200
  batch_size: 16
  epochs: 100
  total_steps: 1000

  lr_init: 5.0e-5
  lr_target: 5.0e-5
  opt_betas: [0.9, 0.95]
  opt_eps: 1.0e-8
  weight_decay: 1.0e-6

  checkpoint_interval: 1000
  eval_interval: 100

  pipeline: "PromptPipeline"
  orchestrator: "OfflineOrchestrator"
  seed: 1000

method:
  name: "ilqlconfig"
  tau: 0.7
  gamma: 0.99
  cql_scale: 0.1
  awac_scale: 1
  alpha: 0.001
  steps_for_target_q_sync: 5
  betas: [4]
  two_qs: true
